Draft integration
k8s-community/github-integration pull request #1
Opened 2017-05-13 18:02 UTC by vsaveliev

Please check our business logic.

2017-05-14 06:36 UTC, takama requested changes
Packages naming should be like as in standard library

2017-05-14 06:36 UTC, takama commented on jenkins_client/client.go
> +package jenkins_client
I believe, you should not use `client` twice, because `client.go` already said about `client`. Just use `jenkins\client.go`. Package: `jenkins`

2017-05-14 06:36 UTC, takama commented on user_manager_client/client.go
> +package user_manager_client
The same way, but add one level of packages: `user/manager/client.go`. Avoid of using `_` in package names. Please see standard library naming conventions.

2017-05-14 06:36 UTC, takama commented on user_manager_client/repository.go
> +package user_manager_client
I think it might be `user/repository/service.go`

2017-05-14 06:36 UTC, takama commented on user_manager_client/response.go
> +package user_manager_client
`user/manager/response.go` ?

2017-05-14 06:36 UTC, takama commented on user_manager_client/user.go
> +package user_manager_client
`user/manager/service.go`?

2017-05-15 04:13 UTC, rumyantseva commented on webhook_handler.go
>  	case "integration_installation":
я бы вынесла case в отдельные функции вообще

2017-05-15 04:15 UTC, rumyantseva commented on handlers.go
> +func (h *handler) authCallbackHandler(w http.ResponseWriter, _ *http.Request) {
Кажется, у меня такой же есть :)

2017-05-17 11:43 UTC, rumyantseva commented on github/client_test.go
> +	privKey := []byte(`-----BEGIN RSA PRIVATE KEY-----
Это что за приватный ключ светится? :)

2017-05-17 11:45 UTC, rumyantseva commented on github/commit_status.go
> +	req, err := http.NewRequest("POST", fmt.Sprintf("%s/repos/%s/%s/statuses/%s", c.baseURL, build.Username, build.Repository, build.CommitHash), b)
А стандартный клиент для гитхаба не подошел?

2017-05-17 11:46 UTC, rumyantseva commented on handlers/base.go
> +func (h *Handler) AuthCallbackHandler(c *router.Control) {
Зачем это здесь?

2017-05-17 11:47 UTC, rumyantseva commented
Не буду особо ничего пока писать про сам код. Предлагаю оставить так. На досуге улучшим то, что надо улучшить по codestyle и т. д.

2017-05-17 11:51 UTC, vsaveliev reviewed
В общих словах хотя бы напиши, мне для себя полезно знать, что не так.

2017-05-17 11:51 UTC, vsaveliev commented on github/commit_status.go
> +	req, err := http.NewRequest("POST", fmt.Sprintf("%s/repos/%s/%s/statuses/%s", c.baseURL, build.Username, build.Repository, build.CommitHash), b)
Не стал использовать ради одной команды, если будем расширять функционал, то будет смысл (ИМХО)

2017-05-17 12:03 UTC, merged